In [34]:
# 1. Import Library yang dibutuhkan
import pandas as pd
import glob
import os

In [35]:
# 2. Hubungkan ke Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [36]:
# 3. Ambil semua file CSV dalam folder
path = '/content/drive/MyDrive/Cyclistic-Bike-Share-Analysis/cyclistic_final_clean.csv'
df_clean = pd.read_csv(path)

# Analyze

In [37]:
df_clean

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,member_casual,ride_length,day_of_week
0,7569BC890583FCD7,classic_bike,2025-01-21 17:23:54.538,2025-01-21 17:37:52.015,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,member,13.957950,3
1,013609308856B7FC,electric_bike,2025-01-11 15:44:06.795,2025-01-11 15:49:11.139,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,member,5.072400,7
2,EACACD3CE0607C0D,classic_bike,2025-01-02 15:16:27.730,2025-01-02 15:28:03.230,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,member,11.591667,5
3,EAA2485BA64710D3,classic_bike,2025-01-23 08:49:05.814,2025-01-23 08:52:40.047,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,member,3.570550,5
4,7F8BE2471C7F746B,electric_bike,2025-01-16 08:38:32.338,2025-01-16 08:41:06.767,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,member,2.573817,5
...,...,...,...,...,...,...,...,...,...,...,...
5552989,53202484E8371237,electric_bike,2025-12-19 13:43:41.793,2025-12-19 13:54:07.779,Sheffield Ave & Kingsbury St,CHI02023,Halsted St & Melrose St,CHI02162,member,10.433100,6
5552990,3582BF76707AB2ED,classic_bike,2025-12-27 12:43:48.446,2025-12-27 12:52:45.141,Larrabee St & Webster Ave,CHI00454,Halsted St & Melrose St,CHI02162,member,8.944917,7
5552991,B12D92DF229EFA41,electric_bike,2025-12-20 01:12:39.053,2025-12-20 01:18:55.928,Clarendon Ave & Junior Ter,CHI00395,Halsted St & Melrose St,CHI02162,casual,6.281250,7
5552992,04D5C6C11909ECAE,electric_bike,2025-12-08 16:46:37.496,2025-12-08 16:58:32.762,Lincoln Ave & Waveland Ave,CHI00446,Halsted St & Wrightwood Ave,CHI00504,member,11.921100,2
5552993,D2CF23B6D79232B6,classic_bike,2025-12-20 13:08:27.589,2025-12-20 13:13:54.815,Larrabee St & Webster Ave,CHI00454,Halsted St & Wrightwood Ave,CHI00504,member,5.453767,7

In [58]:
# Analisis perbandingan Member vs Casual
summary_stats = df_clean.groupby('member_casual')['ride_length'].agg(['mean', 'median', 'max', 'min'])

# Analisis jumlah perjalanan per hari
rides_per_day = df_clean.groupby(['member_casual', 'day_of_week']).size().reset_index(name='total_rides')
rides_per_day = rides_per_day.pivot(index='day_of_week', columns='member_casual', values='total_rides')

# Analisis Rata-rata Durasi per Hari
avg_duration_day = df_clean.groupby(['member_casual', 'day_of_week'])['ride_length'].mean().reset_index(name='avg_duration')
avg_duration_day = avg_duration_day.pivot(index='day_of_week', columns='member_casual', values='avg_duration')

In [59]:
summary_stats

                    mean     median         max       min
member_casual
casual         22.327087  12.815817  1499.63770  0.001167
member         12.346390   8.711533  1498.44835  0.001300

In [60]:
rides_per_day

member_casual  casual  member
day_of_week
1              223546  250674
2              154903  348528
3              148922  383513
4              143202  370688
5              166508  382678
6              210928  348382
7              275249  285514

In [61]:
avg_duration_day

member_casual     casual     member
day_of_week
1              25.788769  13.776916
2              21.926994  11.872281
3              19.804573  12.015035
4              18.238813  11.754910
5              19.672063  11.838083
6              21.994178  12.311572
7              25.093820  13.605966

In [62]:
# Menyimpan hasil ringkasan ke CSV agar tidak perlu memproses data jutaan baris lagi di alat visualisasi
summary_stats.to_csv('summary_statistics.csv', index=False)
rides_per_day.to_csv('rides_by_day.csv')
avg_duration_day.to_csv('duration_by_day.csv')

print("\nFile analisis ringkasan telah berhasil dibuat!")

File analisis ringkasan telah berhasil dibuat!